name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: download
        run: |
          git config --local user.email "loxehate@gmail.com"
          git config --local user.name "loxe"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          pwd
          chmod +x bin/yt-dlp
          ./bin/yt-dlp -v --config-location config.txt
          git add .
          git commit -m "download youtube video"
          git push
